### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by vipconsult** [stevenmaguire/oauth2-microsoft#2]
composer require stevenmaguire/oauth2-microsoft:dev-master

 Problem 1
    - Installation request for stevenmaguire/oauth2-microsoft dev-master -> satisfiable by stevenmaguire/oauth2-microsoft[dev-master].
    - stevenmaguire/oauth2-microsoft dev-master requires league/oauth2-client 1.0.0-beta1 -> no matching package found.

if i run only with 
 composer require stevenmaguire/oauth2-microsoft:dev-master

it installs the old version which is 0.1.0

**Comment by stevenmaguire** [comment]
I've seen the issue also recorded at thephpleague/oauth2-linkedin/issues/1

does your composer.json file include a minimum-stability directive? Both of these packages, the master branches at least, are "dev" stability as I am waiting for the official 1.0 release of thephpleague/oauth2-client, of which they are only useful. In order to install and use these packages in their current state, you will need to allow "dev" stability.

**Comment by vipconsult** [comment]
"minimum-stability":"dev"

ok added this to the oauth-client json 

and now getting

 Problem 1
    - Can only install one of: league/oauth2-client[1.0.x-dev, 1.0.0-beta1].
    - Can only install one of: league/oauth2-client[1.0.0-beta1, 1.0.x-dev].
    - stevenmaguire/oauth2-microsoft 1.0.x-dev requires league/oauth2-client 1.0.0-beta1 -> satisfiable by league/oauth2-client[1.0.0-beta1].
    - Installation request for stevenmaguire/oauth2-microsoft ^1.0@dev -> satisfiable by stevenmaguire/oauth2-microsoft[1.0.x-dev].
    - Installation request for league/oauth2-client 1.0.x-dev -> satisfiable by league/oauth2-client[1.0.x-dev].

**Comment by stevenmaguire** [comment]
Please provide a copy of your composer.json file?

**Comment by vipconsult** [comment]
it is the original from the client
https://github.com/thephpleague/oauth2-client/blob/master/composer.json

and "minimum-stability":"dev",


{
    "name": "league/oauth2-client:1.0.0-beta1",
    "description": "OAuth 2.0 Client Library",
    "license": "MIT",
    "minimum-stability":"dev",
    "require": {
        "php": ">=5.5.0",
        "ext-curl": "*",
        "ircmaxell/random-lib": "~1.1",
        "guzzlehttp/guzzle": "~6.0",
        "league/oauth2-google": "dev-master",
        "league/oauth2-facebook": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "mockery/mockery": "~0.9",
        "squizlabs/php_codesniffer": "~2.0",
        "satooshi/php-coveralls": "0.6.*",
        "jakub-onderka/php-parallel-lint": "0.8.*"
    },
    "keywords": [
        "oauth",
        "oauth2",
        "authorization",
        "authentication",
        "idp",
        "identity",
        "sso",
        "single sign on"
    ],
    "authors": [
        {
            "name": "Alex Bilbie",
            "email": "hello@alexbilbie.com",
            "homepage": "http://www.alexbilbie.com",
            "role": "Developer"
        }
    ],
    "autoload": {
        "psr-4": {
            "League\\OAuth2\\Client\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "League\\OAuth2\\Client\\Test\\": "test/src/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}

**Comment by stevenmaguire** [comment]
"league/oauth2-google": "dev-master" is  "minimum-stability": "beta" and depends on "league/oauth2-client": "~1.0"

"league/oauth2-facebook": "dev-master" depends on "league/oauth2-client": "~1.0@dev"

"stevenmaguire/oauth2-microsoft": "dev-master" depends on "league/oauth2-client": "1.0.0-beta1"

All three of these packages are in a different state of dependency on the same package. Composer is throwing issues because it cannot managed multiple versions of the same package. You will either need to only work with packages that have the same dev dependency or wait until the core package is officially released, and stable, and the provider packages also cut official releases.
